# Generated by Django 2.1.4 on 2018-12-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoviesDB', '0002_auto_20181216_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='film',
            name='genres',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='Movies.MoviesDB.Genre'),
        ),
    ]
